# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'WKWebViewOC' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for WKWebViewOC
  
  inhibit_all_warnings!
  pod 'YYKit', '~> 1.0.9'


  target 'WKWebViewOCTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WKWebViewOCUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
